# Generated by Django 4.2.6 on 2023-10-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
                ('director', models.CharField(blank=True, max_length=500, null=True)),
                ('genres', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('actors', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
